keys:
  # Workstation/Passwortmanager (gleicher Key wie im homelab-kubernetes-Repo)
  - &admin age1yex3n3e9uyyq3r0etnry6glhxave345e47kj77jzgseetn9vefqsn8dw29
  # Host-Keys (ssh-to-age aus /etc/ssh/ssh_host_ed25519_key.pub)
  - &hl02 age1nz400gnh03d8fhq066pa0gj5c6lj6suycke0epct3p7nhycrpdfqqqga4w
  - &hl03 age1hu6u6lnczz4y6ne8m3fcw4spdnc90hhm4k25sf3lshze4yeyjpjs00z5kr
  # Weitere Host-Keys werden je Migrationsphase ergänzt:
  # - &hl01 age1...

creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *admin
          - *hl02
          - *hl03
